### ISSUE TITLE
More granite colors, please?

### ISSUE THREAD

**Issue by CsillaAria** [mrp-v2/AdditionalColors#1]
This is where we are supposed to leave request right? 

I think having dyeable granite would be awesome if you can do that! I really love this mod, and I look forward to seeing what else you do with it.

Thank you!

**Comment by mrp-v2** [comment]
Do you mean regular granite, or polished granite, or both? Also do you want slabs and stairs?

**Comment by CsillaAria** [comment]
Both would be great, as well as slabs and stairs if it's not too much trouble.

**Comment by mrp-v2** [comment]
Added in version 1.16.4-1.3.0.0-forge
