### ISSUE TITLE
Add colored trapdoors and light blocks

### ISSUE THREAD

**Issue by mrp-v2** [mrp-v2/AdditionalColors#2]
From: https://www.curseforge.com/minecraft/mc-mods/additional-colors?comment=32

Specific light blocks: Glowstone, Sea Lantern, Shroomlight

**Comment by mrp-v2** [comment]
Which trapdoors do you want colored versions of?

**Comment by XolfWolf** [comment]
> Which trapdoors do you want colored versions of?

If it is possible I want you to add every wood trapdoor but if not, then please add only nether wood type trapdoor.
Thanks again!

**Comment by mrp-v2** [comment]
Version 1.16.5-1.4.2.0-forge
